#!/usr/bin/env bash
# Lists all active IPv4 IP addresses on the machine
ip_addresses=$(ip -o -4 addr show | awk '{print $4}' | cut -d/ -f1)

IFS=$'\n' read -r -d '' -a ip_addresses <<< "$ip_addresses"

for ip in "${ip_addresses[@]}"; do
  printf '%s\n' "$ip"
done
